### ISSUE TITLE
Is this correctly ignored given that its explicitly listed above?

### ISSUE THREAD

**Issue by netdisciple** [soluble-ai/kubetap#11]
https://github.com/soluble-ai/kubetap/blob/3e4d55c8e3ec1a2c2bb8a6032385f3cf9e7e0524/.goreleaser.yml#L26

Also, i looked at gcr.io/soluble-oss/kubetap-mitmproxy and didnt see any arm64 tag.

Any plans for support?

**Comment by Eriner** [comment]
There isn't an arm64 Docker image, however there are arm64 Linux binaries. Check the latest release, ex: https://github.com/soluble-ai/kubetap/releases/download/v0.1.4/kubetap_v0.1.4_Linux_arm64.tar.gz
